### ISSUE TITLE
微信开发者工具选择音乐播放时控制台重复输出是什么原因？

### ISSUE THREAD

**Issue by qqbrowser** [XieTongXue/mpvue-music#1]
![image](https://user-images.githubusercontent.com/49448223/55813209-ff301b00-5b1e-11e9-8975-498a2ef04322.png)

**Comment by XieTongXue** [comment]
是因为Singer以及SingerDetail都有调用MiniPlayer组件，解决办法是把MiniPlayer的逻辑抽离出来，请pull最新代码
